/**
 * Class for Region.
 */
export enum Region {
  MOURNINGDALE = 'MOURNINGDALE',
  EBONSCALE_REACH = 'EBONSCALE_REACH',
  BRIGHTWOOD = 'BRIGHTWOOD',
  WEAVERS_FEN = 'WEAVERS_FEN',
  RESTLESS_SHORE = 'RESTLESS_SHORE',
  EVERFALL = 'EVERFALL',
  MONARCHS_BLUFFS = 'MONARCHS_BLUFFS',
  WINDSWARD = 'WINDSWARD',
  REEKWATER = 'REEKWATER',
  CUTLASS_KEYS = 'CUTLASS_KEYS',
  FIRST_LIGHT = 'FIRST_LIGHT',
}
